/// <reference types="vite-plugin-pwa/client" />
/// <reference lib="webworker" />

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst } from 'workbox-strategies'

declare let self: ServiceWorkerGlobalScope

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

cleanupOutdatedCaches()

// Fallback for navigation
registerRoute(new NavigationRoute(async ({ request }) => {
  try {
    return await fetch(request)
  } catch {
    return (await caches.match('/offline')) || Response.error()
  }
}))

// Runtime caching for assets (same-origin only)
registerRoute(
  ({ request }) => {
    const url = new URL(request.url)
    return url.origin === self.location.origin &&
      (request.destination === 'script' || request.destination === 'style')
  },
  new NetworkFirst({
    cacheName: 'assets-cache',
    networkTimeoutSeconds: 3,
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          if (response && response.status === 200) return response
          return null
        },
      },
    ],
  })
)

// Runtime caching for images (same-origin only)
registerRoute(
  ({ request }) => {
    const url = new URL(request.url)
    return url.origin === self.location.origin && request.destination === 'image'
  },
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          if (response && response.status === 200) return response
          return null
        },
      },
    ],
  })
)

// Push notification handler
self.addEventListener('push', (event) => {
  if (!event.data) return

  let data: { title?: string; body?: string; url?: string; timestamp?: number }
  try {
    data = event.data.json()
  } catch {
    data = { title: 'AlfredGO', body: event.data.text(), url: '/' }
  }

  const title = data.title || 'AlfredGO'
  const options: NotificationOptions = {
    body: data.body || 'New update from AlfredGO',
    icon: '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    tag: `alfredgo-${data.timestamp || Date.now()}`,
    requireInteraction: false,
    data: {
      url: data.url || '/',
    },
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click handler
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const url = (event.notification.data as any)?.url || '/'

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Focus existing tab if open
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.focus()
            client.postMessage({ type: 'NAVIGATE', url })
            return
          }
        }
        // Otherwise open new window
        self.clients.openWindow(url)
      })
  )
})

// Skip waiting on install
self.addEventListener('install', () => {
  self.skipWaiting()
})

// Claim clients on activate
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})
